version: "3.9"

services:
  mongodb:
    image: mongo:8.0  
    container_name: grabber-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: grabber_admin
      MONGO_INITDB_ROOT_PASSWORD: superSecret123

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
